CREATE sequence hibernate_sequence start with 1 increment by 1

CREATE TABLE Documents (
  id INTEGER NOT NULL,
  name VARCHAR(50),
  path VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE Filters (
  id INTEGER NOT NULL,
  name VARCHAR(255),
  options VARCHAR(255),
  type INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE proposals_products (
  id BIGINT NOT NULL,
  classificatorCode VARCHAR(255),
  classificatorDescription VARCHAR(255),
  classificatorType VARCHAR(255),
  externalId BIGINT,
  name VARCHAR(255),
  okeiCode VARCHAR(255),
  okeiDescription VARCHAR(255),
  positionNumber INTEGER,
  price DECIMAL(19,2),
  quantity DECIMAL(19,2),
  trade_id BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE trades_products (
  id BIGINT NOT NULL,
  classificatorCode VARCHAR(255),
  classificatorDescription VARCHAR(255),
  classificatorType VARCHAR(255),
  externalId BIGINT,
  name VARCHAR(255),
  okeiCode VARCHAR(255),
  okeiDescription VARCHAR(255),
  positionNumber INTEGER,
  price DECIMAL(19,2),
  quantity DECIMAL(19,2),
  summ DECIMAL(19,2),
  trade_id BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE trades (
  id BIGINT generated by default as identity,
  activate_time BIGINT NOT NULL,
  beginDT TIMESTAMP,
  bestPrice DECIMAL(19,2),
  bestProposalId BIGINT,
  CREATE_dt TIMESTAMP,
  endDT TIMESTAMP,
  min_val DECIMAL(11,2) NOT NULL,
  name VARCHAR(255),
  nmc DECIMAL(19,2),
  price_update_dt TIMESTAMP,
  proposal_CREATE_dt TIMESTAMP,
  proposal_id BIGINT,
  proposal_status VARCHAR(255),
  proposalsCount INTEGER,
  status VARCHAR(255),
  trade_id BIGINT NOT NULL,
  update_dt TIMESTAMP,
  user_id BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE Users (
  id BIGINT NOT NULL,
  NDS INTEGER,
  cert_hash VARCHAR(255),
  cert_name VARCHAR(255),
  CREATE_dt TIMESTAMP,
  email VARCHAR(50) NOT NULL,
  fathername VARCHAR(20) NOT NULL,
  fax VARCHAR(25),
  firstname VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  surname VARCHAR(20) NOT NULL,
  use_NDS boolean NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users_documents (
  user_id BIGINT NOT NULL,
  document_id INTEGER NOT NULL
);

ALTER TABLE trades ADD CONSTRAINT UK_trade_user unique (user_id, trade_id);

ALTER TABLE Users ADD CONSTRAINT UK_user_name unique (name);

ALTER TABLE users_documents ADD CONSTRAINT UK_document_id unique (document_id);

ALTER TABLE proposals_products ADD CONSTRAINT FK_trades_proposal_products FOREIGN KEY (trade_id) REFERENCES trades;

ALTER TABLE trades ADD CONSTRAINT FK_users_trades FOREIGN KEY (user_id) REFERENCES Users;

ALTER TABLE trades_products ADD CONSTRAINT FK_trades_trades_products FOREIGN KEY (trade_id) REFERENCES trades;

ALTER TABLE users_documents ADD CONSTRAINT FK_documents_users FOREIGN KEY (document_id) REFERENCES Documents;

ALTER TABLE users_documents ADD CONSTRAINT FK_users_documents FOREIGN KEY (user_id) REFERENCES Users;
